version: '3'

services:
  database:
    image: mysql:8.0.33
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234a
      MYSQL_DATABASE: tiendatest
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  back-end:
    container_name: server-express
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234a
      DATABASE_NAME: tiendatest
    restart: always
    depends_on:
      - database
    ports:
      - 4000:3000
  front-end:
    container_name: front-react
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end
    ports:
      - 3001:3001